name: Deploy when push
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: pull
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: ${{ secrets.COMMAND1 }}
                  host: ${{ secrets.HOST1 }}
                  username: ${{ secrets.USERNAME }}
                  privateKey: ${{ secrets.PRIVATE_KEY1 }}
                  port: ${{ secrets.PORT1 }}
