name: Deploy when push
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: pull
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: echo "test" >> /root/test.log && git -C /root/gym/bupt-gym-reserve pull
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.USERNAME }}
                  passphrase: ${{ secrets.PASSWD }}
